spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 11111111
    url: jdbc:mysql://my-study-instanse.ciokf3otw2lm.ap-northeast-2.rds.amazonaws.com:3306/kopring?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: admin
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update